# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: '%env(resolve:DB_DRIVER)%'
                server_version: '%env(resolve:DB_VERSION)%'
                charset: utf8
                url: '%env(resolve:DATABASE_URL)%'
                persistent: false
            only_read:
                driver: '%env(resolve:DB_DRIVER)%'
                server_version: '%env(resolve:DB_VERSION)%'
                charset: utf8
                url: '%env(resolve:DATABASE_URL_READ)%'
                persistent: false

    orm:        
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            only_read:
                connection: only_read
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
