doctrine_mongodb:
    default_connection: default
    default_document_manager: default
    connections:
        default:
            server: 'mongodb://%env(MONGODB_SERVER)%:%env(MONGODB_PORT)%'
            options:
                username: '%env(MONGO_INITDB_ROOT_USERNAME)%'
                password: '%env(MONGO_INITDB_ROOT_PASSWORD)%'
                authSource: '%env(MONGODB_AUTH_SOURCE)%'

    document_managers:
        default:
            connection: default
            database: symfony
            # metadata_cache_driver: xcache
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
