doctrine_mongodb:
    connections:
        default:
            server: 'mongodb://%env(MONGODB_SERVER)%:%env(MONGODB_PORT)%'
            options:
                username: '%env(MONGODB_USERNAME)%'
                password: '%env(MONGODB_PASSWORD)%'
                authSource: '%env(MONGO_INITDB_DATABASE)%'
    default_database: '%env(MONGO_INITDB_DATABASE)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
