doctrine_mongodb:
    default_connection: default
    default_document_manager: default
    connections:
        default:
            server: 'mongodb://%env(resolve:MONGODB_SERVER)%:%env(resolve:MONGODB_PORT)%'
            # server: 'mongodb://%env(resolve:MONGODB_SERVER)%:%env(resolve:MONGODB_PORT)%/?authSource=admin&readPreference=primary&ssl=false'
            options:
                username: '%env(resolve:MONGO_INITDB_ROOT_USERNAME)%'
                password: '%env(resolve:MONGO_INITDB_ROOT_PASSWORD)%'
                authSource: '%env(resolve:MONGODB_AUTH_SOURCE)%'
    document_managers:
        default:
            connection: default
            database: '%env(resolve:MONGODB_DB_NAME)%'
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
