security:
    providers:
        api_provider:
            id: App\Security\ApiProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        doc:
            pattern: ^/doc
            security: false
        api:
            pattern: ^/
            host: '%env(APP_URL)%'
            provider: api_provider
            stateless: true
            guard:
                authenticators:
                    - App\Security\ApiAuthenticator
    access_control:
        # - { path: ^/state, roles: ["ADMIN"] }
        # - { path: ^/city, roles: ["ADMIN"] }
