security:
    providers:
        api_provider:
            id: App\Security\ApiProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        healthy:
            pattern: healthy
            security: false
        doc:
            pattern: ^/doc
            security: false
        # home:
        #     pattern: /
        #     security: false
        api:
            pattern: ^/
            host: '%env(APP_URL)%'
            provider: api_provider
            stateless: true
            guard:
                authenticators:
                    - App\Security\ApiAuthenticator
    access_control:
        # - { path: ^/auth, roles: [IS_AUTHENTICATED_FULLY] }
        # - { path: ^/state, roles: ROLE_ADMIN }
        # - { path: ^/city, roles: ROLE_ADMIN }
