version: '3.7'
networks:
    challenge:
        driver: bridge
services:
    web:
        image: omrqs/php7.x-sf:php-7.4-dev
        container_name: challenge
        restart: always
        depends_on:
            - redis
            - mysqldb
        ports:
            - ${UPSTREAM_PORT}:${UPSTREAM_PORT}
        links: 
            - redis
            - mysqldb
        volumes:
            - ./:${CONTAINER_PATH}
            - ./docker/custom.ini.local:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/entrypoint.local.sh:${CONTAINER_PATH}/entrypoint.sh
        working_dir: ${CONTAINER_PATH}
        entrypoint: ["sh", "${CONTAINER_PATH}/entrypoint.sh"]
        networks:
            - challenge
    redis:
        image: redis:alpine
        labels:
            com.symfony.server.service-prefix: 'REDIS'
        expose:
            - ${REDIS_PORT}
        networks:
            - challenge
    mysqldb:
        image: mysql:5.7
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - "./var/.mysql/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - challenge
            