version: '3.7'
networks:
    challenge:
        driver: bridge
services:
    web:
        image: omrqs/php7.x-sf:php-7.4-mongodb
        container_name: challenge
        restart: always
        depends_on:
            - redis
            - mongodb
        ports:
            - ${UPSTREAM_PORT}:${UPSTREAM_PORT}
        links: 
            - redis
            - mongodb
        volumes:
            - ./:${CONTAINER_PATH}
            - ./docker/custom.ini.local:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/entrypoint.local.sh:${CONTAINER_PATH}/entrypoint.sh
        working_dir: ${CONTAINER_PATH}
        entrypoint: ["sh", "${CONTAINER_PATH}/entrypoint.sh"]
        networks:
            - challenge
    redis:
        image: redis:alpine
        labels:
            com.symfony.server.service-prefix: 'REDIS'
        expose:
            - ${REDIS_PORT}
        networks:
            - challenge
    mongodb:
        image: mongo
        restart: always
        ports:
            - ${MONGODB_PORT}:${MONGODB_PORT}
        # env_file:
        #     - .env
        labels:
            com.symfony.server.service-prefix: 'MONGO'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - ./var/.mongodb/mongod.conf:/etc/mongod.conf
            - ./var/.mongodb/initdb.d/:/docker-entrypoint-initdb.d/
            - ./var/.mongodb/data/db/:/data/db/
            - ./var/.mongodb/data/log/:/var/log/mongodb/
